import { connectFollowController } from './follow.js';
import { connectIndexController } from './index.js';
import { connectPhotoController } from './entity.js';
import { installLifecycle1 } from './lifecycle.js';
import { clearCatalogGrid, installCatalog7, installCatalog12, installCatalog19 } from './catalog.js';
import { installLayout18 } from './layout.js';
import { installFollow15 } from './follow.js';
import { cancelQueueRequest, installNavigation2, installNavigation4 } from './navigation.js';
import { installLoading3 } from './loading.js';
import { installPreferences5, installPreferences23 } from './preferences.js';
import { installReceipts6 } from './receipts.js';
import { installTutorial8 } from './tutorial.js';
import { installEntity9, installEntity17 } from './entity.js';
import { installMedia10, installMedia21 } from './media.js';
import { installSelection11 } from './selection.js';
import { installFeed13 } from './feed.js';
import { installPlaylists14 } from './playlists.js';
import { installIndex16 } from './index.js';
import { installSearch20, installSearch22 } from './search.js';
import { installComposition24 } from './composition.js';
import { installChrome25 } from './chrome.js';
import { applicationEffects } from './effects';

export function initializeApplication() {
  installLifecycle1();
  installNavigation2();
  installLoading3();
  installNavigation4();
  installPreferences5();
  installReceipts6();
  installCatalog7();
  installTutorial8();
  installEntity9();
  installMedia10();
  installSelection11();
  installCatalog12();
  installFeed13();
  installPlaylists14();
  installFollow15();
  installIndex16();
  installEntity17();
  connectFollowController();
  connectIndexController();
  connectPhotoController();
  installLayout18();
  installCatalog19();
  installSearch20();
  installMedia21();
  installSearch22();
  installPreferences23();
  installComposition24();
  installChrome25();
  applicationEffects.own(clearCatalogGrid);
  applicationEffects.own(cancelQueueRequest);
}
